version: '3.7'
services:
  backend:
    build:
      context: ./Back-End
      dockerfile: Dockerfile
    working_dir: /code
    volumes:
      - ./Back-End:/code
    networks:
      - stack-networks
    ports:
      - 8080:8000


networks:
  stack-networks:
    driver: bridge