/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('primevue/badge')['default']
    Column: typeof import('primevue/column')['default']
    DashboardLayout: typeof import('./src/components/DashboardLayout.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    EmptyLayout: typeof import('./src/components/EmptyLayout.vue')['default']
    EventDataTable: typeof import('./src/components/EventDataTable.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SidebarItem: typeof import('./src/components/SidebarItem.vue')['default']
  }
}
